<?php

/**
 * TProbeTarAsset class file.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @link https://github.com/belisoful/prado-publishing
 * @license https://github.com/pradosoft/prado/blob/master/LICENSE
 */

namespace Prado\Web\Tests\Fixtures;

use Prado\IO\TTarFileExtractor;
use Prado\Web\Assets\TAsset;
use Prado\Web\Assets\TTarAsset;

/**
 * TProbeTarAsset class.
 *
 * A test tar asset. It can be virtual, generating its archive from {@see $archive}; it
 * records where the archive is written and extracted from; its extractor can be
 * replaced through {@see $extractorFactory}; and it exposes the protected TTarAsset
 * methods for direct testing.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 */
class TProbeTarAsset extends TTarAsset
{
	/** @var bool whether the archive is virtual, generated by {@see writeAsset}. */
	public bool $virtual = false;

	/** @var ?string the generated archive content; null fails the write of a virtual archive. */
	public ?string $archive = null;

	/** @var string[] the paths the archive was written to. */
	public array $writtenTo = [];

	/** @var array<array{0:string, 1:bool}> the archive paths extracted from, and whether each existed then. */
	public array $extractedFrom = [];

	/** @var ?\Closure the extractor factory, given the archive path; null for the default. */
	public ?\Closure $extractorFactory = null;

	public function getIsVirtual(): bool
	{
		return $this->virtual;
	}

	public function validatePath(string $filepath)
	{
		return $this->virtual ? TAsset::virtualpath($filepath) : parent::validatePath($filepath);
	}

	public function writeAsset(string $filepath): bool
	{
		$this->writtenTo[] = $filepath;
		if (!$this->virtual) {
			return parent::writeAsset($filepath);
		}
		if ($this->archive === null) {
			file_put_contents($filepath, 'partial');
			return false;
		}
		return file_put_contents($filepath, $this->archive) !== false;
	}

	protected function createExtractor(string $tarPath): TTarFileExtractor
	{
		$this->extractedFrom[] = [$tarPath, is_file($tarPath)];
		return $this->extractorFactory ? ($this->extractorFactory)($tarPath) : parent::createExtractor($tarPath);
	}

	public function probeValidateAssetPath($filepath)
	{
		return $this->validateAssetPath($filepath);
	}

	public static function probeEnsureNullableBoolean($value): ?bool
	{
		return static::ensureNullableBoolean($value);
	}
}
