<?php

/**
 * TTarAsset class file.
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @link https://github.com/belisoful/prado-publishing
 * @license https://github.com/pradosoft/prado/blob/master/LICENSE
 */

namespace Prado\Web\Assets;

use Prado\Exceptions\TInvalidDataValueException;
use Prado\Exceptions\TIOException;
use Prado\IO\TTarFileExtractor;
use Prado\TPropertyValue;

/**
 * TTarAsset class
 *
 * A tar archive published as its extracted directory. The archive is extracted by
 * {@see \Prado\IO\TTarFileExtractor}, so uncompressed, gzip, bzip2, and xz archives are
 * supported, with the extractor's safety checks. The extraction is configured on the
 * asset: {@see setAtomic Atomic} (staged extraction), {@see setStrict Strict},
 * {@see setConflictMode ConflictMode}, {@see setDirMode DirMode}, and
 * {@see setFileMode FileMode}. A property left null takes the publishing manager's
 * option or property when published by {@see \Prado\Web\TPublishingManager}.
 *
 * The archive publishes to the hashed directory of the folder holding its checksum file
 * (or the archive, without one), as {@see \Prado\Web\TAssetManager::publishTarFile} does.
 * The checksum file is published into that directory after the extraction and marks it
 * as extracted; without a checksum file, a completion marker does. With
 * {@see setVerifyChecksum VerifyChecksum}, the archive's MD5 must match the checksum file.
 *
 * Being an asset, the archive can be virtualized, or generated by a subclass whose
 * {@see getIsVirtual IsVirtual} is true: a virtual archive is written to a temporary
 * file by {@see writeAsset} and extracted from there. After the
 * extraction, `onProcessAsset` is raised on the published directory, and
 * {@see getExtractor Extractor} holds the extractor for its manifest and skipped files.
 *
 * ```php
 * $url = $manager->publishTarFile('/path/to/bundle.tar.gz', '/path/to/bundle.md5', ['strict' => true]);
 * $asset = new TTarAsset('/path/to/bundle.tar', '/path/to/bundle.md5');
 * $asset->setConflictMode(TTarFileExtractor::CONFLICT_NEWER);
 * $url = $manager->publish($asset);
 * ```
 *
 * @author Brad Anderson <belisoful@icloud.com>
 * @since 0.1.0
 */
class TTarAsset extends TFileAsset
{
	/** @var ?string the checksum file path. */
	private ?string $_md5FilePath = null;

	/** @var ?bool whether the extraction is staged, null for the manager's. */
	private ?bool $_atomic = null;

	/** @var ?bool whether a malformed archive is rejected, null for the extractor's. */
	private ?bool $_strict = null;

	/** @var mixed the extraction conflict mode, null for the extractor's. */
	private $_conflictMode;

	/** @var ?int the extracted directory mode, null for the manager's. */
	private ?int $_dirMode = null;

	/** @var ?int the extracted file mode, null for the manager's. */
	private ?int $_fileMode = null;

	/** @var bool whether the archive MD5 is verified against the checksum file. */
	private bool $_verifyChecksum = false;

	/** @var ?TTarFileExtractor the extractor of the last extraction. */
	private ?TTarFileExtractor $_extractor = null;

	/**
	 * @param ?string $filePath the tar archive path.
	 * @param ?string $md5FilePath the checksum file path, or null for none.
	 * @param ?string $virtualPath the virtual path of the archive.
	 */
	public function __construct(?string $filePath = null, ?string $md5FilePath = null, ?string $virtualPath = null)
	{
		$this->_md5FilePath = ($md5FilePath === null || $md5FilePath === '') ? null : $md5FilePath;
		parent::__construct($filePath, $virtualPath);
	}

	/**
	 * @return ?string the checksum file path, or null for none.
	 */
	public function getMd5FilePath(): ?string
	{
		return $this->_md5FilePath;
	}

	/**
	 * @param ?string $value the checksum file path, or null for none.
	 */
	public function setMd5FilePath($value): void
	{
		$this->_md5FilePath = ($value === null || $value === '') ? null : TPropertyValue::ensureString($value);
		$this->resetFilePathCache();
	}

	/**
	 * @return ?bool whether the extraction is staged; null for the manager's Atomic.
	 */
	public function getAtomic(): ?bool
	{
		return $this->_atomic;
	}

	/**
	 * @param null|bool|string $value whether the extraction is staged; null for the manager's.
	 */
	public function setAtomic($value): void
	{
		$this->_atomic = static::ensureNullableBoolean($value);
	}

	/**
	 * @return ?bool whether a malformed archive is rejected; null for the extractor default.
	 */
	public function getStrict(): ?bool
	{
		return $this->_strict;
	}

	/**
	 * @param null|bool|string $value whether a malformed archive is rejected; null for the default.
	 */
	public function setStrict($value): void
	{
		$this->_strict = static::ensureNullableBoolean($value);
	}

	/**
	 * @return mixed the conflict mode, a TTarFileExtractor::CONFLICT_* value or callable;
	 *   null for the extractor default.
	 */
	public function getConflictMode()
	{
		return $this->_conflictMode;
	}

	/**
	 * @param mixed $value the conflict mode: a TTarFileExtractor::CONFLICT_* value, its
	 *   name ("Skip", "Overwrite", ...), a callable, or null for the default.
	 * @throws TInvalidDataValueException when the name is not a conflict mode.
	 */
	public function setConflictMode($value): void
	{
		if ($value === null || $value === '') {
			$this->_conflictMode = null;
			return;
		}
		if (is_string($value) && !is_numeric($value) && !is_callable($value)) {
			$constant = TTarFileExtractor::class . '::CONFLICT_' . strtoupper(trim($value));
			if (!defined($constant)) {
				throw new TInvalidDataValueException('tarasset_conflictmode_invalid', $value);
			}
			$value = constant($constant);
		} elseif (is_numeric($value)) {
			$value = (int) $value;
		}
		$this->_conflictMode = $value;
	}

	/**
	 * @return ?int the extracted directory mode; null for the manager's DirMode.
	 */
	public function getDirMode(): ?int
	{
		return $this->_dirMode;
	}

	/**
	 * @param null|int|string $value the extracted directory mode; null for the manager's.
	 */
	public function setDirMode($value): void
	{
		$this->_dirMode = ($value === null || $value === '') ? null : TPropertyValue::ensureInteger($value);
	}

	/**
	 * @return ?int the extracted file mode; null for the manager's FileMode.
	 */
	public function getFileMode(): ?int
	{
		return $this->_fileMode;
	}

	/**
	 * @param null|int|string $value the extracted file mode; null for the manager's.
	 */
	public function setFileMode($value): void
	{
		$this->_fileMode = ($value === null || $value === '') ? null : TPropertyValue::ensureInteger($value);
	}

	/**
	 * @return bool whether the archive's MD5 must match the checksum file, default false.
	 */
	public function getVerifyChecksum(): bool
	{
		return $this->_verifyChecksum;
	}

	/**
	 * @param bool|string $value whether the archive's MD5 must match the checksum file.
	 */
	public function setVerifyChecksum($value): void
	{
		$this->_verifyChecksum = TPropertyValue::ensureBoolean($value);
	}

	/**
	 * @return ?TTarFileExtractor the extractor of the last extraction, for its manifest
	 *   and skipped files; null before extracting.
	 */
	public function getExtractor(): ?TTarFileExtractor
	{
		return $this->_extractor;
	}

	/**
	 * Fills the extraction settings left null from publishing options. The keys are
	 * those of {@see \Prado\Web\TAssetManager::publishTarFile}: atomic, strict,
	 * conflictMode, dirMode, and fileMode.
	 * @param array $options the publishing options.
	 */
	public function applyPublishingOptions(array $options): void
	{
		if ($this->_atomic === null && array_key_exists('atomic', $options)) {
			$this->setAtomic($options['atomic']);
		}
		if ($this->_strict === null && array_key_exists('strict', $options)) {
			$this->setStrict($options['strict']);
		}
		if ($this->_conflictMode === null && array_key_exists('conflictMode', $options)) {
			$this->setConflictMode($options['conflictMode']);
		}
		if ($this->_dirMode === null && array_key_exists('dirMode', $options)) {
			$this->setDirMode($options['dirMode']);
		}
		if ($this->_fileMode === null && array_key_exists('fileMode', $options)) {
			$this->setFileMode($options['fileMode']);
		}
	}

	/**
	 * The archive publishes as the directory holding its checksum file, or the archive.
	 * @return null|false|string the published directory path, with a trailing separator.
	 */
	public function getAssetPublishFilePath()
	{
		$path = parent::getAssetPublishFilePath();
		if (!is_string($path) || $path === '') {
			return $path;
		}
		$md5 = $this->getMd5FileRealPath();
		return dirname($md5 ?? $path) . DIRECTORY_SEPARATOR;
	}

	/**
	 * @throws TInvalidDataValueException when the checksum file does not exist.
	 * @return ?string the real path of the checksum file, or null without one.
	 */
	public function getMd5FileRealPath(): ?string
	{
		if ($this->_md5FilePath === null) {
			return null;
		}
		if (($path = realpath($this->_md5FilePath)) === false || !is_file($path)) {
			throw new TInvalidDataValueException('assetmanager_tarchecksum_invalid', $this->_md5FilePath);
		}
		return $path;
	}

	/**
	 * The path the completion marker of the extracted archive is keyed by: the checksum
	 * file, or the archive itself without a checksum file. As in
	 * {@see \Prado\Web\TAssetManager::publishTarFile}, the published checksum file is not
	 * the marker: publishing that same checksum file on its own puts an identical copy in
	 * the same place, which says nothing about whether the archive was ever extracted.
	 * @throws TInvalidDataValueException when the checksum file does not exist.
	 * @return string the path the marker is keyed by.
	 */
	public function getExtractedMarkerSource(): string
	{
		return $this->getMd5FileRealPath() ?? (string) $this->getAssetFilePath();
	}

	/**
	 * Validates the checksum file, then the archive.
	 * @param false|string $filepath the archive path.
	 * @throws TInvalidDataValueException when the checksum file does not exist.
	 * @throws TIOException when the archive does not exist.
	 * @return null|false|string the archive path.
	 */
	protected function validateAssetPath($filepath)
	{
		if ($filepath === null || $filepath === false) {
			return $filepath;
		}
		$this->getMd5FileRealPath();
		$path = parent::validateAssetPath($filepath);
		if ($path === false || ($path !== null && !$this->getIsVirtual() && !is_file($path))) {
			throw new TIOException('assetmanager_tarfile_invalid', $filepath);
		}
		return $path;
	}

	/**
	 * @return false|int the modification time of the checksum file, or else the archive.
	 */
	public function getAssetModificationDate()
	{
		if (($md5 = $this->getMd5FileRealPath()) !== null && $this->getAssetFilePath()) {
			return $this->dyGetAssetModificationDate(@filemtime($md5));
		}
		return parent::getAssetModificationDate();
	}

	/**
	 * Extracts the archive into the directory, publishes the checksum file into it, and
	 * raises `onProcessAsset` on the directory.
	 * @param string $dst the published directory.
	 * @throws TInvalidDataValueException when the archive path is invalid or $dst is empty.
	 * @throws TIOException when the checksum does not match, or the archive cannot be extracted.
	 * @return ?bool whether the archive was extracted; false when cancelled, or the value
	 *   a dyWriteAsset handler returns.
	 */
	public function publish(string $dst): ?bool
	{
		if (($src = $this->getAssetFilePath()) === false) {
			throw new TInvalidDataValueException('asset_assetfilepath_invalid', $src);
		}
		if ($src === null) {
			return false;
		}
		if ($dst === '') {
			throw new TInvalidDataValueException('asset_dst_filepath_invalid', $dst);
		}
		if (($return = $this->dyWriteAsset(0, $dst)) !== 0) {
			return $return;
		}
		$tarPath = $this->getAssetOriginalFilePath();
		$md5 = $this->getMd5FileRealPath();
		$temporary = null;
		if ($this->getIsVirtual()) {
			if (!is_dir(dirname($dst))) {
				@mkdir(dirname($dst), $this->_dirMode ?? 0o777, true);
			}
			$temporary = dirname($dst) . DIRECTORY_SEPARATOR . 'tmp-' . uniqid('', true) . '-' . basename($src);
			$tarPath = $temporary;
		}
		try {
			if ($temporary !== null && !$this->writeAsset($temporary)) {
				throw new TIOException('assetmanager_tarfile_invalid', $src);
			}
			if ($this->_verifyChecksum && $md5 !== null) {
				$expected = strtolower((string) strtok((string) file_get_contents($md5), " \t\r\n*"));
				if ($expected !== md5_file($tarPath)) {
					throw new TIOException('tarasset_checksum_mismatch', $tarPath, $md5);
				}
			}
			if (!is_dir($dst)) {
				@mkdir($dst, $this->_dirMode ?? 0o777, true);
			}
			$extractor = $this->createExtractor($tarPath);
			$this->configureExtractor($extractor);
			$this->_extractor = $extractor;
			if (!$extractor->extract($dst)) {
				throw new TIOException('tarasset_extract_failed', $tarPath, $dst);
			}
		} finally {
			if ($temporary !== null) {
				@unlink($temporary);
			}
		}
		if ($md5 !== null) {
			$tmp = $dst . DIRECTORY_SEPARATOR . 'tmp-' . uniqid('', true) . '-' . basename($md5);
			if (@copy($md5, $tmp) && !@rename($tmp, $dst . DIRECTORY_SEPARATOR . basename($md5))) {
				@unlink($tmp);
			}
			if ($this->_fileMode !== null) {
				@chmod($dst . DIRECTORY_SEPARATOR . basename($md5), $this->_fileMode);
			}
		}
		$this->onProcessAsset($dst);
		return true;
	}

	/**
	 * Creates the extractor for an archive. Override to customize the extractor beyond
	 * the asset's properties, e.g. its exception class or URL timeout.
	 * @param string $tarPath the archive path.
	 * @return TTarFileExtractor the extractor.
	 */
	protected function createExtractor(string $tarPath): TTarFileExtractor
	{
		return new TTarFileExtractor($tarPath);
	}

	/**
	 * Applies the asset's extraction settings to an extractor.
	 * @param TTarFileExtractor $extractor the extractor.
	 */
	protected function configureExtractor(TTarFileExtractor $extractor): void
	{
		if ($this->_atomic !== null) {
			$extractor->setAtomic($this->_atomic);
		}
		if ($this->_strict !== null) {
			$extractor->setStrict($this->_strict);
		}
		if ($this->_conflictMode !== null) {
			$extractor->setConflictMode($this->_conflictMode);
		}
		$extractor->setDirModeOverride($this->_dirMode);
		$extractor->setFileModeOverride($this->_fileMode);
	}

	/**
	 * @param mixed $value the value.
	 * @return ?bool null for null or '', else the boolean.
	 */
	protected static function ensureNullableBoolean($value): ?bool
	{
		return ($value === null || $value === '') ? null : TPropertyValue::ensureBoolean($value);
	}
}
